### ISSUE TITLE
Refactor cross-mapping related structure

### ISSUE THREAD

**Issue by gajagajago** [mcrl/spipe#20]
`cm_rank` and `pp_rank` is extremely confusing. 

Current status is that `cm rank` is used for cross mapping pipeline rank ordering, while pp rank is the rank in pipeline model parallel group. 

However, its querying APIs are used in somewhat mixed manner. 
- get_pipeline_model_parallel_rank -> cm rank
- get_pipeline_model_parallel_first/last_rank -> pp rank
- get_pipeline_model_parallel_prev/next_rank -> pp rank

We currently use `translate_cm_rank_to_pp_rank` to translate the cm rank (usually during communication requests), but this should be refactored since it is suuuuuuper confusing. While doing refactoring, carefully look at various places, including training.py training_log where lm loss is printed by the last cm rank process.

**Comment by gajagajago** [comment]
There is currently some... wild... errors in NRR mapping. Look at slurm-751903.out amd 751905.out for them

````
[rank26]: Traceback (most recent call last):
[rank26]:   File "/home/s6/junyeol/spipe/Megatron-LM-mcrl/pretrain_gpt.py", line 116, in <module>
[rank26]:     pretrain(train_valid_test_datasets_provider,
[rank26]:   File "/home/s6/junyeol/spipe/Megatron-LM-mcrl/megatron/training.py", line 212, in pretrain
[rank26]:     iteration = train(forward_step_func,
[rank26]:   File "/home/s6/junyeol/spipe/Megatron-LM-mcrl/megatron/training.py", line 1244, in train
[rank26]:     train_step(forward_step_func,
[rank26]:   File "/home/s6/junyeol/spipe/Megatron-LM-mcrl/megatron/training.py", line 832, in train_step
[rank26]:     losses_reduced = forward_backward_func(
[rank26]:   File "/home/s6/junyeol/spipe/Megatron-LM-mcrl/megatron/spiral/schedules.py", line 506, in forward_backward_pipelining_with_spiral_remap
[rank26]:     input_tensor, recv_handles = spiral_p2p.recv_input_tensor(
[rank26]:   File "/home/s6/junyeol/miniconda3/envs/pytorch-2.3-cuda-12.1-python-3.8/lib/python3.8/site-packages/nvtx/nvtx.py", line 116, in inner
[rank26]:     result = func(*args, **kwargs)
[rank26]:   File "/home/s6/junyeol/spipe/Megatron-LM-mcrl/megatron/spiral/p2p_communication.py", line 222, in recv_input_tensor
[rank26]:     input_tensor = _self_send_recv_input_tensor_store.popleft()
[rank26]: IndexError: pop from an empty deque
```
